server: 
  port: 8083
eureka:
  client:
    service-url: 
      defaultZone: ${EUREKA_SERVER:http://localhost:8761/eureka/}
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true    
spring:
  h2:
    console:
      enabled: true
  datasource: 
    url: jdbc:h2:mem:productservice
    driver-class-name: org.h2.Driver
    username: sa
    password: 
  jpa: 
    spring: 
       jpa.database-platform: org.hibernate.dialect.H2Dialect             
  config: 
     import: configserver:http://localhost:9292         