-- CREATE SEQUENCE IF NOT EXISTS product_id_seq START WITH 1 INCREMENT BY 1;

-- CREATE TABLE PRODUCT
-- (
--     PRODUCT_ID  BIGINT NOT NULL,
--     PRODUCT_NAME VARCHAR(255),
--     QUANTITY BIGINT,
--     PRODUCT_PRICE BIGINT,
--     CONSTRAINT pk_product PRIMARY KEY (PRODUCT_ID)
-- );


INSERT INTO PRODUCT(PRODUCT_ID,PRODUCT_NAME,QUANTITY,PRODUCT_PRICE) VALUES(1111,'Redmi',20,15000);
INSERT INTO PRODUCT(PRODUCT_ID,PRODUCT_NAME,QUANTITY,PRODUCT_PRICE) VALUES(2111,'Apple-Iphone',15,50000);
INSERT INTO PRODUCT(PRODUCT_ID,PRODUCT_NAME,QUANTITY,PRODUCT_PRICE) VALUES(3111,'Dell-Laptop',36,85000);
INSERT INTO PRODUCT(PRODUCT_ID,PRODUCT_NAME,QUANTITY,PRODUCT_PRICE) VALUES(4111,'Refridgerator',11,20000);
INSERT INTO PRODUCT(PRODUCT_ID,PRODUCT_NAME,QUANTITY,PRODUCT_PRICE) VALUES(5111,'Samsung',29,12000);
INSERT INTO PRODUCT(PRODUCT_ID,PRODUCT_NAME,QUANTITY,PRODUCT_PRICE) VALUES(6111,'FZ-x',12,185000);
INSERT INTO PRODUCT(PRODUCT_ID,PRODUCT_NAME,QUANTITY,PRODUCT_PRICE) VALUES(7111,'MemoryCard',134,6000);